"""create saved releases table

Revision ID: e148620e4753
Revises: 
Create Date: 2026-07-11 18:07:33.573367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e148620e4753'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_releases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_login', sa.String(length=100), nullable=False),
    sa.Column('experience_mode', sa.String(length=16), nullable=False),
    sa.Column('selection_mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('repository', sa.String(length=255), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('generate_for', sa.String(length=16), nullable=False),
    sa.Column('selected_author', sa.String(length=255), nullable=False),
    sa.Column('release_range', sa.String(length=32), nullable=True),
    sa.Column('date_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('fixes', sa.JSON(), nullable=False),
    sa.Column('improvements', sa.JSON(), nullable=False),
    sa.Column('documentation', sa.JSON(), nullable=False),
    sa.Column('maintenance', sa.JSON(), nullable=False),
    sa.Column('contributors', sa.JSON(), nullable=False),
    sa.Column('selected_commit_ids', sa.JSON(), nullable=False),
    sa.Column('selected_commits', sa.JSON(), nullable=False),
    sa.Column('total_commits', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("experience_mode IN ('lite', 'advanced')", name='ck_saved_releases_experience_mode'),
    sa.CheckConstraint("generate_for IN ('all', 'individual')", name='ck_saved_releases_generate_for'),
    sa.CheckConstraint("selection_mode IN ('automatic', 'manual')", name='ck_saved_releases_selection_mode'),
    sa.CheckConstraint("status IN ('draft', 'final', 'published')", name='ck_saved_releases_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_releases_experience_mode'), 'saved_releases', ['experience_mode'], unique=False)
    op.create_index(op.f('ix_saved_releases_owner_login'), 'saved_releases', ['owner_login'], unique=False)
    op.create_index('ix_saved_releases_owner_updated', 'saved_releases', ['owner_login', 'updated_at'], unique=False)
    op.create_index(op.f('ix_saved_releases_repository'), 'saved_releases', ['repository'], unique=False)
    op.create_index('ix_saved_releases_repository_updated', 'saved_releases', ['repository', 'updated_at'], unique=False)
    op.create_index(op.f('ix_saved_releases_status'), 'saved_releases', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_releases_status'), table_name='saved_releases')
    op.drop_index('ix_saved_releases_repository_updated', table_name='saved_releases')
    op.drop_index(op.f('ix_saved_releases_repository'), table_name='saved_releases')
    op.drop_index('ix_saved_releases_owner_updated', table_name='saved_releases')
    op.drop_index(op.f('ix_saved_releases_owner_login'), table_name='saved_releases')
    op.drop_index(op.f('ix_saved_releases_experience_mode'), table_name='saved_releases')
    op.drop_table('saved_releases')
    # ### end Alembic commands ###
